#!/bin/bash

TOMCAT_INIT=/etc/init.d/tomcat7;
OLD_DEPLOYMENT=/usr/share/tomcat7/webapps/ROOT

#get changes from git
git pull;

#shutdown tomcat while we redeploy
sudo $TOMCAT_INIT stop;

#remove previous build
sudo rm -r "$OLD_DEPLOYMENT";
sudo rm "$OLD_DEPLOYMENT.war";

#build with dependencies
sudo mvn package;

#start tomcat again
sudo $TOMCAT_INIT start;

#remove target dir
sudo mvn clean;